name: Deploy to Render

on:
  push:
    tags:
      - 'v*'
      
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  pre_deployment_checks:
    name: Run Tests & Validations
    runs-on: ubuntu-24.04
    if: >
      github.event_name == 'push' || 
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
        
      - name: Execute test suite
        run: |
          echo "Validando que todas las pruebas pasan antes del despliegue..."

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-24.04
    needs: [pre_deployment_checks]
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Trigger Render Deploy Hook
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"